"""
MadXka Discord lookup bot.

Commands (all built on the bubbablox-v2 API that madxka.com runs):

  /user    lookup a MadXka user by username or user ID   -> headshot embed
  /item    lookup a catalog item by ID or keyword        -> thumbnail embed
  /game    lookup a game by universe/place ID or keyword -> icon embed
  /avatar  lookup a user's full-body avatar              -> full avatar image

Users that are verified get bubba's verified badge next to their name, staff
(admin) get the bubbablox admin shield, and both together show both badges
side by side. The badge SVGs are the original bubbablox-v2 assets served by
the Render proxy (proxy/proxy.py) at {base}/badges/*.svg.

Talk to the Render proxy, not madxka.com directly:
  1. deploy proxy/ on Render (render.yaml)
  2. set MADXKA_BASE_URL=https://<your-service>.onrender.com in .env

Run:
  python bot.py        (DISCORD_TOKEN in env or .env)
"""

from __future__ import annotations

import logging
import os
import time
from pathlib import Path

import aiohttp
import discord
from discord import app_commands
from discord.ext import commands

import madxka

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
COOLDOWN_SECONDS = 5.0

# All command descriptions are temporary on purpose.
CMD_DESCRIPTION = "yh basically the name all ts temp tho"

EMBED_COLOR = discord.Color(0x2B7FFF)          # the one neet accent
ERROR_COLOR = discord.Color(0xFF4D4D)
FOOTER_TEXT = "MadXka • bubbablox v2"

TYPE_EMOJI = {
    "Hat": "🧢",
    "Head": "🙂",
    "Face": "😀",
    "Shirt": "👕",
    "TeeShirt": "👕",
    "Pants": "👖",
    "Gear": "⚙️",
    "Model": "📦",
    "Image": "🖼️",
    "Audio": "🎵",
    "GamePass": "🎟️",
    "Place": "🗺️",
    "HairAccessory": "💇",
    "FaceAccessory": "🕶️",
    "NeckAccessory": "📿",
    "ShoulderAccessory": "🎒",
    "FrontAccessory": "🦺",
    "BackAccessory": "🎒",
    "WaistAccessory": "🧷",
}


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------
def load_dotenv_file(path: Path) -> None:
    """Minimal .env loader (KEY=VALUE lines) so we don't need python-dotenv."""
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_dotenv_file(Path(__file__).with_name(".env"))

TOKEN = os.environ.get("DISCORD_TOKEN")
if not TOKEN:
    raise SystemExit(
        "Missing DISCORD_TOKEN. Put it in the environment or in a .env file "
        "(see .env.example)."
    )
BASE_URL = os.environ.get("MADXKA_BASE_URL", madxka.DEFAULT_BASE_URL)
GUILD_ID = os.environ.get("DISCORD_GUILD_ID") or None

# Badge assets (original bubbablox-v2 files) served by the Render proxy:
# verified: bubba's verified.svg | admin: bubbablox admin_icon_11222016.svg
# (png = 1:1 render of the svg, generated by make_badges_png.py)
VERIFIED_BADGE_URL = f"{BASE_URL}/badges/verified.png"
ADMIN_BADGE_URL = f"{BASE_URL}/badges/admin.png"
# local copies of the same files, attached when a user has BOTH badges
# (Discord lays the two image attachments out side by side)
_BADGES_DIR = Path(__file__).with_name("proxy") / "badges"
VERIFIED_BADGE_FILE = _BADGES_DIR / "verified.png"
ADMIN_BADGE_FILE = _BADGES_DIR / "admin.png"

# madxka/bubbablox exposes staff as isStaff on some builds; upstream bubba
# models it as isAdmin/isModerator — accept any of them.
STAFF_FIELDS = ("isStaff", "staff", "isAdmin", "isModerator")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
log = logging.getLogger("madxka-bot")


def fmt_num(value) -> str:
    try:
        return f"{int(value):,}"
    except (TypeError, ValueError):
        return "0"


def fmt_dt(value) -> str:
    parsed = madxka.parse_datetime(value)
    if parsed is None:
        return "unknown"
    return discord.utils.format_dt(parsed)


def base_embed(title: str) -> discord.Embed:
    embed = discord.Embed(
        title=title[:256],
        color=EMBED_COLOR,
        timestamp=discord.utils.utcnow(),
    )
    embed.set_footer(text=FOOTER_TEXT)
    return embed


def error_embed(message: str) -> discord.Embed:
    embed = discord.Embed(description=message[:1024], color=ERROR_COLOR)
    embed.set_footer(text="MadXka lookup failed")
    return embed


# simple per-user cooldown so the madxka api isn't hammered
_cooldowns: dict[int, float] = {}


def on_cooldown(user_id: int) -> bool:
    now = time.monotonic()
    last = _cooldowns.get(user_id, 0.0)
    if now - last < COOLDOWN_SECONDS:
        return True
    _cooldowns[user_id] = now
    if len(_cooldowns) > 50_000:  # safety prune
        _cooldowns.clear()
    return False


def truncate(text: str, limit: int = 1024) -> str:
    text = (text or "").strip()
    if len(text) <= limit:
        return text or "No description."
    return text[: limit - 1].rstrip() + "…"


def badge_flags(user: dict) -> tuple[bool, bool]:
    verified = bool(user.get("isVerified"))
    staff = any(bool(user.get(key)) for key in STAFF_FIELDS)
    return verified, staff


def apply_badges(embed: discord.Embed, user: dict) -> list[discord.File]:
    """Attach the user's badge(s); returns the message files to send.

    one badge -> shown in the author row, right next to the username
    both      -> the two original badges as two separate images, side by side
    """
    verified, staff = badge_flags(user)
    if not verified and not staff:
        return []
    if verified != staff:  # exactly one of the two
        url = VERIFIED_BADGE_URL if verified else ADMIN_BADGE_URL
        name = str(user.get("name") or user.get("displayName") or "")[:128]
        embed.set_author(name=name, icon_url=url)
        return []
    # both: no author icon — send the two originals as separate attachments
    return [
        discord.File(VERIFIED_BADGE_FILE, filename="verified.png"),
        discord.File(ADMIN_BADGE_FILE, filename="admin.png"),
    ]


async def resolve_user(client: madxka.MadxkaClient, query: str) -> dict | None:
    """Resolve a username or numeric user id to the full user info dict."""
    query = query.strip()
    if query.isdigit():
        return await client.get_user(int(query))
    entry = await client.get_user_by_username(query)
    if not entry or not entry.get("id"):
        return None
    info = await client.get_user(int(entry["id"]))
    # fall back to the username lookup entry if the detail call 404s
    if not info:
        return {"id": entry["id"], "name": entry.get("name"),
                "displayName": entry.get("displayName")}
    return info


# ---------------------------------------------------------------------------
# Embed builders
# ---------------------------------------------------------------------------
async def build_user_embed(client, query: str) -> discord.Embed | None:
    user = await resolve_user(client, query)
    if not user or not user.get("id"):
        return None
    user_id = int(user["id"])
    name = user.get("displayName") or user.get("name") or query

    headshots = await client.get_user_headshots([user_id])
    status_text = await client.get_user_status_text(user_id)

    embed = base_embed(f"👤 {name}")
    embed.url = f"{BASE_URL}/users/{user_id}"
    badge_files = apply_badges(embed, user)
    headshot = headshots.get(user_id)
    if headshot:
        embed.set_thumbnail(url=headshot)

    embed.add_field(name="Username", value=f"`{user.get('name') or query}`", inline=True)
    embed.add_field(name="User ID", value=f"`{user_id}`", inline=True)
    embed.add_field(name="Joined", value=fmt_dt(user.get("created")), inline=True)
    embed.add_field(name="Verified", value="✅" if user.get("isVerified") else "❌", inline=True)
    if user.get("totalrap") is not None:
        embed.add_field(name="RAP", value=f"💎 {fmt_num(user['totalrap'])}", inline=True)
    embed.add_field(
        name="Status",
        value="🔨 Banned" if user.get("isBanned") else "✅ Active",
        inline=True,
    )
    if status_text:
        embed.add_field(name="Status message", value=truncate(status_text, 1024), inline=False)
    embed.add_field(name="About", value=truncate(user.get("description")), inline=False)
    return embed, badge_files


async def build_item_embed(client, query: str) -> discord.Embed | None:
    query = query.strip()
    others: list[dict] = []
    if query.isdigit():
        details = await client.get_item_details([int(query)])
        if not details:
            return None
        item = details[0]
    else:
        results = await client.search_items(query, limit=6)
        if not results:
            return None
        ids = [int(r["id"]) for r in results if r.get("id") is not None]
        details = await client.get_item_details(ids)
        if not details:
            return None
        by_id = {int(d["id"]): d for d in details}
        item = by_id.get(int(results[0]["id"])) or details[0]
        for r in results[1:]:
            if r.get("id") is not None and int(r["id"]) in by_id:
                others.append(by_id[int(r["id"])])

    asset_id = int(item["id"])
    name = item.get("name") or f"Item {asset_id}"
    type_name = madxka.ASSET_TYPES.get(item.get("assetType"), "Unknown")
    emoji = TYPE_EMOJI.get(type_name, "📦")

    thumbs = await client.get_item_thumbnails([asset_id])
    thumb = thumbs.get(asset_id)

    embed = base_embed(f"{emoji} {name}")
    embed.url = f"{BASE_URL}/catalog/{asset_id}"
    if thumb:
        embed.set_thumbnail(url=thumb)

    price = item.get("price")
    if item.get("isForSale"):
        price_value = f"R${fmt_num(price)}" if price else "Free"
    else:
        price_value = "Not for sale"

    embed.add_field(name="Asset ID", value=f"`{asset_id}`", inline=True)
    embed.add_field(name="Type", value=type_name, inline=True)
    embed.add_field(name="Creator", value=str(item.get("creatorName") or "unknown"), inline=True)
    embed.add_field(name="Price", value=price_value, inline=True)
    if item.get("favoriteCount") is not None:
        embed.add_field(name="Favorites", value=f"⭐ {fmt_num(item['favoriteCount'])}", inline=True)
    if item.get("saleCount") is not None:
        embed.add_field(name="Sales", value=f"💰 {fmt_num(item['saleCount'])}", inline=True)

    restrictions = item.get("itemRestrictions") or []
    is_limited = any(r in ("Limited", "LimitedUnique") for r in restrictions)
    if is_limited:
        limited_value = "🔥 LimitedUnique" if "LimitedUnique" in restrictions else "🔥 Limited"
        units = item.get("unitsAvailableForConsumption")
        serials = item.get("serialCount")
        if units is not None:
            limited_value += f"\n{fmt_num(units)} left"
        elif serials:
            limited_value += f"\nof {fmt_num(serials)} serials"
        embed.add_field(name="Limited", value=limited_value, inline=True)
        if item.get("lowestPrice") is not None:
            embed.add_field(name="Lowest price", value=f"R${fmt_num(item['lowestPrice'])}", inline=True)

    embed.add_field(name="Created", value=fmt_dt(item.get("createdAt")), inline=True)
    embed.add_field(name="Updated", value=fmt_dt(item.get("updatedAt")), inline=True)
    if item.get("is18Plus"):
        embed.add_field(name="Age", value="⚠️ 18+", inline=True)

    embed.add_field(name="Description", value=truncate(item.get("description")), inline=False)
    if others:
        lines = [f"`{int(o['id'])}` {o.get('name') or 'item'}" for o in others[:4]]
        embed.add_field(name="More results", value="\n".join(lines), inline=False)
    return embed, []


async def build_game_embed(client, query: str) -> discord.Embed | None:
    query = query.strip()
    player_count = None

    if query.isdigit():
        candidate = int(query)
        universe_id = None
        place_id = None
        games = await client.get_games([candidate])
        if games:
            universe_id = int(games[0]["id"])
        else:
            places = await client.get_place_details([candidate])
            if places:
                universe_id = int(places[0]["universeId"])
                place_id = candidate
        if universe_id is None:
            return None
    else:
        results = await client.search_games(query, max_rows=6)
        if not results:
            return None
        top = results[0]
        universe_id = int(top["universeId"])
        place_id = top.get("placeId") or None
        player_count = top.get("playerCount")

    games = await client.get_games([universe_id])
    if not games:
        return None
    game = games[0]
    place_id = place_id or game.get("rootPlaceId")

    icons = await client.get_game_icons([universe_id])
    votes = await client.get_game_votes([universe_id])

    name = game.get("name") or f"Game {universe_id}"
    embed = base_embed(f"🎮 {name}")
    embed.url = f"{BASE_URL}/games/{place_id}"
    icon = icons.get(universe_id)
    if icon:
        embed.set_thumbnail(url=icon)

    embed.add_field(name="Universe ID", value=f"`{universe_id}`", inline=True)
    embed.add_field(name="Place ID", value=f"`{place_id}`" if place_id else "unknown", inline=True)
    creator = game.get("creator") or {}
    embed.add_field(
        name="Creator",
        value=str(creator.get("name") or "unknown"),
        inline=True,
    )
    if player_count is not None:
        embed.add_field(name="Players", value=f"👥 {fmt_num(player_count)}", inline=True)
    if game.get("visits") is not None:
        embed.add_field(name="Visits", value=f"👣 {fmt_num(game['visits'])}", inline=True)
    if game.get("favoritedCount") is not None:
        embed.add_field(name="Favorites", value=f"⭐ {fmt_num(game['favoritedCount'])}", inline=True)

    vote = votes.get(universe_id)
    if vote:
        up, down = int(vote.get("upVotes") or 0), int(vote.get("downVotes") or 0)
        total = up + down
        pct = f"{(up / total) * 100:.0f}%" if total else "n/a"
        embed.add_field(name="Votes", value=f"👍 {fmt_num(up)} / 👎 {fmt_num(down)} • {pct}")

    embed.add_field(name="Genre", value=madxka.genre_name(game.get("genre")), inline=True)
    if game.get("maxPlayers"):
        embed.add_field(name="Max players", value=f"👥 {fmt_num(game['maxPlayers'])}", inline=True)
    if game.get("price"):
        embed.add_field(name="Price", value=f"R${fmt_num(game['price'])}", inline=True)
    if game.get("year"):
        embed.add_field(name="Year", value=str(game["year"]), inline=True)
    embed.add_field(name="Created", value=fmt_dt(game.get("created")), inline=True)
    embed.add_field(name="Updated", value=fmt_dt(game.get("updated")), inline=True)
    embed.add_field(name="Description", value=truncate(game.get("description")), inline=False)
    return embed, []


async def build_avatar_embed(client, query: str) -> discord.Embed | None:
    user = await resolve_user(client, query)
    if not user or not user.get("id"):
        return None
    user_id = int(user["id"])
    name = user.get("displayName") or user.get("name") or query

    avatars = await client.get_user_full_avatars([user_id])
    headshots = await client.get_user_headshots([user_id])
    full_body = avatars.get(user_id)
    headshot = headshots.get(user_id)
    if not full_body and not headshot:
        return None

    embed = base_embed(f"🖼️ {name}'s Avatar")
    embed.url = f"{BASE_URL}/users/{user_id}"
    badge_files = apply_badges(embed, user)
    embed.set_image(url=full_body or headshot)
    if full_body and headshot:
        embed.set_thumbnail(url=headshot)

    embed.add_field(name="Username", value=f"`{user.get('name') or query}`", inline=True)
    embed.add_field(name="User ID", value=f"`{user_id}`", inline=True)
    embed.add_field(name="Joined", value=fmt_dt(user.get("created")), inline=True)
    return embed, badge_files


# ---------------------------------------------------------------------------
# Bot + commands
# ---------------------------------------------------------------------------
intents = discord.Intents.default()
bot = commands.Bot(command_prefix=commands.when_mentioned, intents=intents)


async def run_lookup(interaction: discord.Interaction, builder):
    """Shared defer -> build embed -> edit flow with friendly errors."""
    user_id = interaction.user.id
    if on_cooldown(user_id):
        await interaction.response.send_message(
            "⏳ slow down! try again in a few seconds.", ephemeral=True
        )
        return
    await interaction.response.defer()
    try:
        result = await builder()
        if result is None:
            embed = error_embed(
                "😕 **Not found** — I couldn't find that on MadXka. "
                "Double-check the name/ID and try again."
            )
            files = []
        else:
            embed, files = result
        await interaction.edit_original_response(embed=embed, files=files or None)
    except madxka.MadxkaError as exc:
        await interaction.edit_original_response(embed=error_embed(f"⚠️ {exc}"))
    except discord.HTTPException:
        log.exception("discord HTTP error in run_lookup")


@bot.tree.command(name="user", description=CMD_DESCRIPTION)
@app_commands.describe(username_or_id="MadXka username or user ID")
async def user_lookup(interaction: discord.Interaction, username_or_id: str):
    """Look up a MadXka user — embed uses the user's headshot."""
    await run_lookup(interaction, lambda: build_user_embed(bot.client, username_or_id))


@bot.tree.command(name="item", description=CMD_DESCRIPTION)
@app_commands.describe(name_or_id="Item name to search for, or the item ID")
async def item_lookup(interaction: discord.Interaction, name_or_id: str):
    """Look up a MadXka catalog item — embed uses the item thumbnail."""
    await run_lookup(interaction, lambda: build_item_embed(bot.client, name_or_id))


@bot.tree.command(name="game", description=CMD_DESCRIPTION)
@app_commands.describe(name_or_id="Game name to search for, or a universe/place ID")
async def game_lookup(interaction: discord.Interaction, name_or_id: str):
    """Look up a MadXka game — embed uses the game icon."""
    await run_lookup(interaction, lambda: build_game_embed(bot.client, name_or_id))


@bot.tree.command(name="avatar", description=CMD_DESCRIPTION)
@app_commands.describe(username_or_id="MadXka username or user ID")
async def avatar_lookup(interaction: discord.Interaction, username_or_id: str):
    """Look up a user's full-body avatar image."""
    await run_lookup(interaction, lambda: build_avatar_embed(bot.client, username_or_id))


@bot.tree.error
async def on_app_command_error(
    interaction: discord.Interaction, error: app_commands.AppCommandError
):
    if isinstance(error, app_commands.CommandInvokeError):
        error = error.original
    if isinstance(error, (madxka.MadxkaError, discord.HTTPException)):
        return  # already handled (or nothing to do)
    log.exception("unhandled app command error", exc_info=error)
    message = "🤔 something went wrong on my end. try again in a bit."
    if interaction.response.is_done():
        await interaction.followup.send(message, ephemeral=True)
    else:
        await interaction.response.send_message(message, ephemeral=True)


@bot.event
async def setup_hook():
    if GUILD_ID:
        await bot.tree.sync(guild=discord.Object(id=int(GUILD_ID)))
        log.info("commands synced to guild %s (instant)", GUILD_ID)
    else:
        await bot.tree.sync()
        log.info("global commands synced (may take a few minutes to show up)")


@bot.event
async def on_ready():
    log.info("logged in as %s (id=%s)", bot.user, bot.user.id)
    log.info("madxka base url: %s", BASE_URL)
    log.info("commands: %s", ", ".join(c.name for c in bot.tree.get_commands()))


async def main():
    session = aiohttp.ClientSession()
    try:
        bot.client = madxka.MadxkaClient(BASE_URL, session=session)
        await bot.start(TOKEN)
    finally:
        await bot.close()
        await session.close()


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
