"""
MadXka API proxy — deploy on Render (https://render.com).

Why: the Discord bot (bot.py) talks to this proxy instead of madxka.com
directly. The proxy:

  * forwards every request to the MadXka instance (MADXKA_UPSTREAM,
    default https://madxka.com) with a normal browser User-Agent and a
    safe Accept-Encoding (gzip/deflate — MadXka/Cloudflare answers some
    requests with brotli, which the bot side cannot decode);
  * serves the original bubbablox-v2 badge assets at stable urls:

      /badges/verified.svg  /badges/verified.png
      /badges/admin.svg     /badges/admin.png

    verified = bubbablox source: public/verified.svg
    admin    = bubbablox source: api/public/images/Logo/admin_icon_11222016.svg

    The originals are bundled in proxy/badges/ (exact copies of the
    bubbablox-v2 files; the .png files are a 1:1 render of the .svg files,
    generated by make_badges_png.py, because Discord only reliably previews
    png images). The bytes are also embedded in this file as a guaranteed
    fallback, so the badge endpoints work no matter what the build context
    includes. .svg endpoints first try MadXka's live copy.
  * GET /health  -> {"ok": true, "upstream": ...}  (Render health check)
  * GET /debug   -> what the proxy sees (upstream, badge files, etc.)

Run locally:
  pip install -r requirements.txt
  python proxy.py            # listens on $PORT (default 10000)
"""
import base64
import os
from pathlib import Path

import aiohttp
from aiohttp import web

UPSTREAM = os.environ.get("MADXKA_UPSTREAM", "https://madxka.com").rstrip("/")
PORT = int(os.environ.get("PORT", "10000"))
BADGES_DIR = Path(__file__).parent / "badges"

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

# request headers worth forwarding upstream.
# NOTE: accept-encoding is deliberately NOT forwarded — we always ask
# upstream for gzip/deflate only (see UPSTREAM_ACCEPT_ENCODING).
FORWARDED_HEADERS = {
    "user-agent",
    "accept",
    "content-type",
    "cookie",
    "authorization",
    "x-csrftoken",
}
UPSTREAM_ACCEPT_ENCODING = "gzip, deflate"

# response headers worth forwarding to the client
RESP_HEADERS = {"content-type", "cache-control", "content-disposition", "set-cookie"}

# (badge name, upstream path on madxka)
BADGE_UPSTREAM_PATHS = {
    "verified": "/verified.svg",
    "admin": "/images/Logo/admin_icon_11222016.svg",
}


# ---------------------------------------------------------------------------
# Embedded original badge bytes — same files as proxy/badges/*, inlined so
# the badge endpoints never depend on the build context including them.
# Regenerate after touching proxy/badges/:
#   python3 - <<'EOF'
#   import base64
#   for n in ("verified.png", "admin.png"):
#       print(n, base64.b64encode(open(f"proxy/badges/{n}", "rb").read()).decode())
#   EOF
# ---------------------------------------------------------------------------
_EMBEDDED_PNG = {
    "verified.png": (
        "iVBORw0KGgoAAAANSUhEUgAAADgAAAA4CAYAAACohjseAAADQ0lEQVR4nN2aTWvUQBiAn0y73bbbd"
        "ItCQbEoCApFUUQRRRHn5B/wrNRt6s2fI9Z/41/w6MW7txVra919PSTtZrP5mCSTSeoDS3fb7Mw8feedz"
        "Ec8TNmTO2zylaPo86HnGX+3RZZLXKnnrg5Ezt93WNZcUNCcZPwtLgudEjZvyL6M8fAr1dKisFnFI3nOkC"
        "/8tFSrQ2GzLqrQVmt1mL9mgoLmuKEWNJy/xYXtiU+PMVJ4ZTPUFC6OoELjA+M61dSgZnc2E5yULbYhKnT"
        "nYsEm868uBsL5/4E9uc6A75k3+C4Tyarcizw0q06a0xj5ggrNH0ctaYh8QTqcf4ZkDzIjuc8GV/nlsDUJ5"
        "NP8Z+/A8IuxwSYvgpql8o2yRVIu63dFZAuqnOXRBSJbMG/91zBVIpVFuuBINJus2avGDkY5mLjZpw8ytp"
        "dHJUiLnvHgkkJ6BAXN7+qFVsVm1zxjUfCdXGKZJ/y1X1keWXJ1ogdpgh6aQb1Cy2JNLmWyvSjoeHnUVOT"
        "OWBRsKf/i2JKDpGAgN1njNlN7FeRhdcTMWPzOC07R9CtWUJImRsw05u+DhtOzypPgjO9XLceE+QgaTM/q"
        "ToJdykFccF8e4bPdxvZgbbmczaeZoKALl781sT0NM0HF3hmt3rMaVNRNXQ0qScLQBtJDOMIrcZyGeUQaz"
        "7vCLjpFMywnB2YybcrBrIvqqjf3PEnXI2YaoaBXb/eslW5piOK9bLPCw7rLI5OGu5YDUEzQrNspzLmAwe"
        "GLAjSn9urMkmwjegCqbv6lcSaT/NkGHh9E2l7/VcLwMFTRa7ol7aJYofgI5gKj+MEhE76xBmwCq5R5PKj"
        "zzFRGcgvQKDSCxucyCjiGzp0RlngYIfvCQB4jaLxIeIhiSijseM90ASuCcV5Jn51IVKHp8YB14JRQ2NEm"
        "1TnWBZMEcoUpGqIID7jBMmFXdnEi3LhgkgPZnRP2GQKhrMVZElD6YaBmxstAnp3nr8cLfGBCKFx317wTgn"
        "FeywZbsfztc5dVZt257CZX5wSTvJUdViLhMH+vsQScRK88Kjyr1v4t/UDuJfI3XLyl5e+FFEwSyEskinCP"
        "pwyY5e/H/0EwzhvZoh/Jguazt1u2iH8a1OhoTl4VTgAAAABJRU5ErkJggg=="
    ),
    "admin.png": (
        "iVBORw0KGgoAAAANSUhEUgAAAJgAAACYCAYAAAAYwiAhAAADIklEQVR4nO3dTXLTQBCA0YbiFFCwgfufC"
        "DZQ5Bqw4KccRSlLsnqmZ/TeARJJ/mqmrchxBAAAAAAAAAAAAAAAML3vn9//6n0M7POm9wHssRbYp29PQ53"
        "D1Qzz4mxdvQRXyzAvxpHtUWz9DfMCnDF/Ca69YS54xoAvuHxDXOBW7x4Fd74hLmiv2xOCe9wQF7DK/S/B"
        "7TfEBasS2C2xbVP+IlWMa43g1pW/KKMEtiS4P8pfhFEDW7pqcOVPepbAlq4SXOmTnDWuNbMGV/qkrhTYr"
        "ZliK30iVw1saeTgSh+4wNaNFFzZAxXXdpWDK3tgAjuuUnBlDmRJYOfpGZzALqZ1bCUDE1c72cEJjGfODu"
        "7tmT8MlgTGfxnbZbnAbI9zKRcYcxEYqQRGROTdrigVmPlrPqUCYz4CI1WZwGyP/WT+uahMYMxJYKQSGKl"
        "KBGb+6if7cZ0SgTEvgZFKYKTqHpj5q58Wz+d3D4y5CYxUAiNV18Cqzl8fv/7sfQjpWn0+8l2LXzKiZWQ/"
        "vnzodCRjE9hGgjum6wdvK26Rj2yPo0TX8t8HdFvBKsb1KKvcS95FkkpgpBLYjTNvT1TdHlv/+6Yugc04f"
        "7HOCkYqgZFKYH+Zv3I0D8z8dS1WMFIJjFRNA6u6PXo8J48V7GRVB/xeBEYqz4PF81XnCttlS8325arz1z1"
        "7g6u4Rfb8riIr2B17VreKcfUmsB2WAdlO7xPYA0aY3Xp/d2STd5Gjzl972B7XuU1BKoGRSmAT6z1/RTQI7"
        "ArzF6+zgpFKYKQS2KQqzF8RyYGZv7CCkUpgpBLYhKrMXxGJgZm/iLCCkUxgpBLYZCrNXxFJgZm/+McKRi"
        "qBkUpgE6k2f0UkBGb+4pYVjFTpS6oVrY2K22NEh6+SEVwOgb1CcOcQ2EaCO0ZgBwnuvqpxRQwQ2JLgXhJ"
        "YIsEJrKkrBiewjmYPrnJcERcIbGm24ARW3OjBCWwwowUnsMFVDq56XBEC261ScAK7gJ7BCeyCWgYnMNKCG"
        "yGuCIE1d1ZwAmOTo8EJjEO2BicwTrEW3ChxMaBK9+EAAAAAAAAAAAAAAIA8vwF0DyNIFGp2jwAAAABJRU5"
        "ErkJggg=="
    ),
}
_EMBEDDED_SVG = {
    "verified.svg": (
        "<svg xmlns='http://www.w3.org/2000/svg' width='28' height='28' viewBox='0 0 28 28' "
        "fill='none'><g clip-path='url(#clip0_8_46)'><rect x='5.88818' width='22.89' height="
        "'22.89' transform='rotate(15 5.88818 0)' fill='#0066FF'/><path fill-rule='evenodd' "
        "clip-rule='evenodd' d='M20.543 8.7508L20.549 8.7568C21.15 9.3578 21.15 10.3318 20."
        "549 10.9328L11.817 19.6648L7.45 15.2968C6.85 14.6958 6.85 13.7218 7.45 13.1218L7.45"
        "7 13.1148C8.058 12.5138 9.031 12.5138 9.633 13.1148L11.817 15.2998L18.367 8.7508C18."
        "968 8.1498 19.942 8.1498 20.543 8.7508Z' fill='white'/></g><defs><clipPath id='clip0_"
        "8_46'><rect width='28' height='28' fill='white'/></clipPath></defs></svg>"
    ),
    "admin.svg": (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<svg version="1.1" id="ROBLOX" xmlns="http://www.w3.org/2000/svg" '
        'xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="76px" height="76px" '
        'viewBox="0 0 76 76" style="enable-background:new 0 0 76 76;" xml:space="preserve">\n'
        '<style type="text/css">\n'
        "\t.st0{fill:#E2231A;}\n"
        "</style>\n"
        '<path class="st0" d="M21.6,10.4L10.3,54.5l44.1,11.4l11.4-44.1L21.6,10.4z M41.2,43.5'
        'l-8.6-2.2l2.2-8.6l8.6,2.2L41.2,43.5z"/>\n'
        "</svg>\n"
    ),
}


class BadgeStore:
    """Serves badge files: live from madxka when possible, else bundled copy."""

    def __init__(self, session: aiohttp.ClientSession) -> None:
        self.session = session
        self._upstream_cache: dict[str, bytes] = {}

    def _local_or_embedded(self, name: str, ext: str) -> bytes:
        """File on disk if the image has it, else the embedded original."""
        path = BADGES_DIR / f"{name}.{ext}"
        try:
            if path.exists():
                return path.read_bytes()
        except OSError:
            pass
        if ext == "png":
            return base64.b64decode(_EMBEDDED_PNG[f"{name}.png"])
        return _EMBEDDED_SVG[f"{name}.svg"].encode("utf-8")

    async def get(self, name: str, ext: str) -> tuple[bytes, str] | None:
        if name not in ("verified", "admin") or ext not in ("svg", "png"):
            return None
        if ext == "png":
            # pngs are only the local 1:1 render of the original svg
            return self._local_or_embedded(name, "png"), "image/png"
        # svg: try madxka's live copy first, fall back to the bundled original
        if name in self._upstream_cache:
            return self._upstream_cache[name], "image/svg+xml"
        data: bytes | None = None
        if self.session is not None:
            try:
                async with self.session.get(
                    UPSTREAM + BADGE_UPSTREAM_PATHS[name],
                    headers={
                        "User-Agent": USER_AGENT,
                        "Accept": "image/svg+xml",
                        "Accept-Encoding": UPSTREAM_ACCEPT_ENCODING,
                    },
                    timeout=aiohttp.ClientTimeout(total=15),
                ) as resp:
                    if resp.status == 200:
                        text = (await resp.text()).strip()
                        if text.startswith("<svg") or text.startswith("<?xml"):
                            data = text.encode("utf-8")
            except aiohttp.ClientError:
                data = None
        if data is None:
            data = self._local_or_embedded(name, "svg")
        self._upstream_cache[name] = data
        return data, "image/svg+xml"


async def health(_request: web.Request) -> web.Response:
    return web.json_response({"ok": True, "upstream": UPSTREAM})


async def debug(_request: web.Request) -> web.Response:
    """What the running image actually has — used to check deployments."""
    try:
        files = sorted(p.name for p in BADGES_DIR.iterdir()) if BADGES_DIR.exists() else []
    except OSError as exc:
        files = [f"<unreadable: {exc!r}>"]
    return web.json_response(
        {
            "ok": True,
            "upstream": UPSTREAM,
            "proxy_file": os.path.abspath(__file__),
            "badges_dir": str(BADGES_DIR),
            "badge_files_on_disk": files,
            "embedded_fallbacks": sorted(list(_EMBEDDED_PNG) + list(_EMBEDDED_SVG)),
        }
    )


async def badge(request: web.Request) -> web.Response:
    store: BadgeStore = request.app["badges"]
    try:
        result = await store.get(request.match_info["name"], request.match_info["ext"])
    except Exception as exc:  # self-diagnosing: show the error instead of a bare 500
        return web.Response(status=500, text=f"badge error: {exc!r}")
    if result is None:
        return web.Response(status=404, text="unknown badge")
    data, content_type = result
    return web.Response(body=data, content_type=content_type,
                        headers={"Cache-Control": "public, max-age=3600"})


async def proxy(request: web.Request) -> web.StreamResponse:
    """Pass the request (path, query, method, body) through to madxka."""
    url = UPSTREAM + request.raw_path
    body = await request.read()
    headers = {k: v for k, v in request.headers.items() if k.lower() in FORWARDED_HEADERS}
    headers["User-Agent"] = USER_AGENT
    headers["Accept-Encoding"] = UPSTREAM_ACCEPT_ENCODING
    session: aiohttp.ClientSession = request.app["session"]
    try:
        async with session.request(
            request.method,
            url,
            headers=headers,
            data=body or None,
            timeout=aiohttp.ClientTimeout(total=30),
        ) as resp:
            payload = await resp.read()
            out = {k: v for k, v in resp.headers.items() if k.lower() in RESP_HEADERS}
            return web.Response(status=resp.status, body=payload, headers=out)
    except aiohttp.ClientError as exc:
        return web.Response(status=502, text=f"upstream error: {exc}")


async def on_startup(app: web.Application) -> None:
    app["session"] = aiohttp.ClientSession()
    app["badges"] = BadgeStore(app["session"])


async def on_cleanup(app: web.Application) -> None:
    await app["session"].close()


def create_app() -> web.Application:
    app = web.Application()
    app.on_startup.append(on_startup)
    app.on_cleanup.append(on_cleanup)
    app.router.add_get("/health", health)
    app.router.add_get("/debug", debug)
    app.router.add_get("/badges/{name}.{ext}", badge)  # name/ext validated in BadgeStore
    app.router.add_route("*", "/{tail:.*}", proxy)
    return app


if __name__ == "__main__":
    web.run_app(create_app(), host="0.0.0.0", port=PORT)
