"""
MadXka API proxy — deploy on Render (https://render.com).

Why: the Discord bot (bot.py) talks to this proxy instead of madxka.com
directly. The proxy:

  * forwards every request to the MadXka instance (MADXKA_UPSTREAM,
    default https://madxka.com) with a normal browser User-Agent, so the
    /apisite/... endpoints and /images/thumbnails/... work cleanly;
  * serves the original bubbablox-v2 badge assets at stable urls:

      /badges/verified.svg  /badges/verified.png
      /badges/admin.svg     /badges/admin.png

    verified = bubbablox source: public/verified.svg
    admin    = bubbablox source: api/public/images/Logo/admin_icon_11222016.svg

    The originals are bundled in proxy/badges/ (exact copies of the
    bubbablox-v2 files; the .png files are a 1:1 render of the .svg files,
    generated by make_badges_png.py, because Discord only reliably previews
    png images). The .svg endpoints first try to fetch the current file from
    MadXka itself and fall back to the bundled copy (MadXka's own middleware
    400s non-.png paths under /images, and /verified.svg is flaky from some
    networks).
  * GET /health -> {"ok": true, "upstream": ...}  (Render health check)

Run locally:
  pip install -r requirements.txt
  python proxy.py            # listens on $PORT (default 10000)
"""
import os
from pathlib import Path

import aiohttp
from aiohttp import web

UPSTREAM = os.environ.get("MADXKA_UPSTREAM", "https://madxka.com").rstrip("/")
PORT = int(os.environ.get("PORT", "10000"))
BADGES_DIR = Path(__file__).parent / "badges"

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

# request headers worth forwarding upstream
FORWARDED_HEADERS = {
    "user-agent",
    "accept",
    "accept-encoding",
    "content-type",
    "cookie",
    "authorization",
    "x-csrftoken",
}

# response headers worth forwarding to the client
RESP_HEADERS = {"content-type", "cache-control", "content-disposition", "set-cookie"}

# (badge name, upstream path on madxka) — .svg served from upstream when
# available, else the bundled original; .png is the bundled 1:1 render.
BADGE_UPSTREAM_PATHS = {
    "verified": "/verified.svg",
    "admin": "/images/Logo/admin_icon_11222016.svg",
}


class BadgeStore:
    """Serves badge files: live from madxka when possible, bundled copy otherwise."""

    def __init__(self, session: aiohttp.ClientSession) -> None:
        self.session = session
        self._upstream_cache: dict[str, bytes | None] = {}

    async def get(self, name: str, ext: str) -> tuple[bytes, str] | None:
        if name not in ("verified", "admin") or ext not in ("svg", "png"):
            return None
        if ext == "png":
            # pngs are only the local 1:1 render of the original svg
            data = (BADGES_DIR / f"{name}.png").read_bytes()
            return data, "image/png"
        # svg: try madxka's live copy first, fall back to the bundled original
        if name not in self._upstream_cache:
            data: bytes | None = None
            if self.session is not None:
                try:
                    async with self.session.get(
                        UPSTREAM + BADGE_UPSTREAM_PATHS[name],
                        headers={"User-Agent": USER_AGENT, "Accept": "image/svg+xml"},
                        timeout=aiohttp.ClientTimeout(total=15),
                    ) as resp:
                        if resp.status == 200:
                            text = (await resp.text()).strip()
                            if text.startswith("<svg") or text.startswith("<?xml"):
                                data = text.encode("utf-8")
                except aiohttp.ClientError:
                    data = None
            if data is None:
                data = (BADGES_DIR / f"{name}.svg").read_bytes()
            self._upstream_cache[name] = data
        return self._upstream_cache[name], "image/svg+xml"


async def health(_request: web.Request) -> web.Response:
    return web.json_response({"ok": True, "upstream": UPSTREAM})


async def badge(request: web.Request) -> web.Response:
    store: BadgeStore = request.app["badges"]
    result = await store.get(request.match_info["name"], request.match_info["ext"])
    if result is None:
        return web.Response(status=404, text="unknown badge")
    data, content_type = result
    return web.Response(body=data, content_type=content_type,
                        headers={"Cache-Control": "public, max-age=3600"})


async def proxy(request: web.Request) -> web.StreamResponse:
    """Pass the request (path, query, method, body) through to madxka."""
    url = UPSTREAM + request.raw_path
    body = await request.read()
    headers = {k: v for k, v in request.headers.items() if k.lower() in FORWARDED_HEADERS}
    headers["User-Agent"] = USER_AGENT
    session: aiohttp.ClientSession = request.app["session"]
    try:
        async with session.request(
            request.method,
            url,
            headers=headers,
            data=body or None,
            timeout=aiohttp.ClientTimeout(total=30),
        ) as resp:
            payload = await resp.read()
            out = {k: v for k, v in resp.headers.items() if k.lower() in RESP_HEADERS}
            return web.Response(status=resp.status, body=payload, headers=out)
    except aiohttp.ClientError as exc:
        return web.Response(status=502, text=f"upstream error: {exc}")


async def on_startup(app: web.Application) -> None:
    app["session"] = aiohttp.ClientSession()
    app["badges"] = BadgeStore(app["session"])


async def on_cleanup(app: web.Application) -> None:
    await app["session"].close()


def create_app() -> web.Application:
    app = web.Application()
    app.on_startup.append(on_startup)
    app.on_cleanup.append(on_cleanup)
    app.router.add_get("/health", health)
    app.router.add_get("/badges/{name}.{ext}", badge)  # name/ext validated in BadgeStore
    app.router.add_route("*", "/{tail:.*}", proxy)
    return app


if __name__ == "__main__":
    web.run_app(create_app(), host="0.0.0.0", port=PORT)
